export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  CATALOG: '/catalog',
  PRODUCT: '/product/:id',
  FITTING_ROOM: '/fitting-room',
  RECOMMENDATIONS: '/recommendations',
  PROFILE: '/profile',
  LOGIN: '/login',
  REGISTER: '/register',
  AVATAR_SETUP: '/avatar-setup',
  ADMIN: '/admin',
  ASSISTANT: '/assistant',
  UNAUTHORIZED: '/unauthorized',
} as const;