import type { Product } from '../../types/product';

export const mockProducts: Product[] = [
  {
    id: 1,
    title: 'Мужская базовая футболка',
    description: 'Удобная базовая футболка для повседневного образа.',
    price: 8990,
    oldPrice: 10990,
    image:
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
    category: 'male',
    type: 'tshirt',
    avatarSlot: 'top',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['white', 'black', 'gray'],
    rating: 4.7,
    isPopular: true,
  },
  {
    id: 2,
    title: 'Мужская джинсовая куртка',
    description: 'Стильная джинсовая куртка для современного гардероба.',
    price: 24990,
    image:
      'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=900&q=80',
    category: 'male',
    type: 'jacket',
    avatarSlot: 'outerwear',
    sizes: ['M', 'L', 'XL'],
    colors: ['blue', 'black'],
    rating: 4.8,
    isNew: true,
  },
  {
    id: 3,
    title: 'Мужские классические брюки',
    description: 'Классические брюки для делового и повседневного стиля.',
    price: 18990,
    image:
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80',
    category: 'male',
    type: 'pants',
    avatarSlot: 'bottom',
    sizes: ['M', 'L', 'XL'],
    colors: ['black', 'navy'],
    rating: 4.5,
  },
  {
    id: 4,
    title: 'Мужские кроссовки',
    description: 'Комфортные кроссовки для активного образа жизни.',
    price: 29990,
    oldPrice: 35990,
    image:
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    category: 'male',
    type: 'sneakers',
    avatarSlot: 'footwear',
    sizes: ['40', '41', '42', '43', '44'],
    colors: ['white', 'red', 'black'],
    rating: 4.9,
    isPopular: true,
  },
  {
    id: 5,
    title: 'Женское платье',
    description: 'Элегантное платье для прогулок и особых случаев.',
    price: 21990,
    image:
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80',
    category: 'female',
    type: 'dress',
    avatarSlot: 'dress',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['beige', 'pink', 'black'],
    rating: 4.8,
    isNew: true,
  },
  {
    id: 6,
    title: 'Женская юбка',
    description: 'Легкая юбка для женственного и стильного образа.',
    price: 14990,
    image:
      'https://images.unsplash.com/photo-1583496661160-fb5886a13d24?auto=format&fit=crop&w=900&q=80',
    category: 'female',
    type: 'skirt',
    avatarSlot: 'bottom',
    sizes: ['XS', 'S', 'M'],
    colors: ['black', 'gray'],
    rating: 4.4,
  },
  {
    id: 7,
    title: 'Женская рубашка',
    description: 'Современная рубашка для офиса и повседневного ношения.',
    price: 12990,
    oldPrice: 15990,
    image:
      'https://images.unsplash.com/photo-1551232864-3f0890e580d9?auto=format&fit=crop&w=900&q=80',
    category: 'female',
    type: 'shirt',
    avatarSlot: 'top',
    sizes: ['S', 'M', 'L'],
    colors: ['white', 'blue'],
    rating: 4.6,
    isPopular: true,
  },
  {
    id: 8,
    title: 'Женские туфли',
    description: 'Классические туфли для завершения стильного образа.',
    price: 26990,
    image:
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80',
    category: 'female',
    type: 'shoes',
    avatarSlot: 'footwear',
    sizes: ['36', '37', '38', '39'],
    colors: ['black', 'nude'],
    rating: 4.7,
  },
];